### ISSUE TITLE
set default precision for coordinates?

### ISSUE THREAD

**Issue by drewda** [rgeo/rgeo-geojson#23]
Is it possible to set a default max number of decimal places to include in latitude/longitude values being serialized?

**Comment by BuonOmo** [comment]
@drewda we could do that, however I think this should be part of RGeo rather than RGeo::GeoJSON. Using GEOS' [`GeometryPrecisionReducer`](https://geos.osgeo.org/doxygen/classgeos_1_1precision_1_1GeometryPrecisionReducer.html).

This could look like:

```ruby
RGeo::GeoJSON.decode(some_geojson).geometry.update_precision(6)
```

There are also postgis functions for that. For instance `ST_Force2D` will remove extra coordinates and round to 6 digits.

I'm closing the current issue. If you still want such a feature, please mention this issue in a new one directly in https://github.com/rgeo/rgeo.
